### ISSUE TITLE
Adding units?

### ISSUE THREAD

**Issue by nneuss** [Ramarren/unit-formula#6]
Hello,
I (or, more precisely, a student of mine) wanted to add units as follows:
    (define-units volume-a (1 ml))
    (define-units volume-b (2 ml))
    (define-units total-volume (+ volume-a volume-b))
... which does not work ("cannot add units of different dimensions").  However, as much as I see, the dimensions should fit?
Thank you,
Nicolas

**Comment by nneuss** [comment]
OK, I looked more carefully.  There is a trivial bug in add-units.  The error function is called indiscriminately, but it should be called only when same-units-p is nil, that is in the same way as in subtract-units.

**Comment by Ramarren** [comment]
I fixed it. Fortunately it was a trivial bug, because I haven't really look at the code since I finished my master's thesis almost ten years ago. I'm glad this is useful for someone other than me.
